# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "vmd"
        "xhci_pci"
        "ahci"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];

      luks = {
        fido2Support = false;

        devices = {
          "luks-d3272da5-cf20-401d-9d15-c5b1ac7fae09" = {
            device = "/dev/disk/by-uuid/d3272da5-cf20-401d-9d15-c5b1ac7fae09";

            crypttabExtraOpts = [
              "fido2-device=auto"
            ];
          };
        };
      };
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/5968883f-50a2-43a8-ac32-28420088e57d";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/9C85-F65E";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
