wireguard:
  serverPrivateKey: ENC[AES256_GCM,data:FIoIMzJ+zNK01SGBD3xuMFX5Q3jRcMFa5VMDwzftQmM9ZxzIKQg9wfnISlA=,iv:vyes2ICKICfznzgr5Aazg1DLKLv3YZsQygFtXKLdngk=,tag:pxx0CSYQZAGhb9NUcijRXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbmRwVzB3VWtoYUdkdnY4
        MU53VFczQTcwNnNEL0dpeWZEQVU3Tm5DM1FRCm03dlB5b1JwWTF0c0JPbTB1bWtY
        VXltZkJ3eFlBc29OSkVFb3RVTC9uMFEKLS0tIHNnNnRLOVRIRnZ3U1ZEMUZ6VVRF
        RTA2TnhMaUdqajcyd0haaXVrVyt0dEEKLt4zDmVZ/ES7TXfLfBEiAOsq0bgz3n5M
        D+eNOMIpXaB3x3wmOr+/Mt67xXrKM96Eo+DyUkYpUSjE6/kyNEBCmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1t2kdsj60j3rc0duru349m6th7tnvhhtf6ywql472kkw8rrf8ze3qnsk6xn
  lastmodified: "2026-06-19T12:08:45Z"
  mac: ENC[AES256_GCM,data:Rv/yFZrCplDLHIShzhaQOqbhFKFoXfpYj/4UQB27vNTj1fGTDTCHgPrYV72ifWtK/6TOmWhgFf3CloF8uFVMIWL7EjbZe8IhdoKJ435kldXLgWj6WFSat0+KJr42tSe+BZXBkYg1QdrKxOCeOtdk1chLgJqsuu4E+q4g95NGHp0=,iv:ESotIDVau9U3oIj7T+6xhOfjZigRCr3cYG7bzhFVI90=,tag:IdctZc9yn0eQGIzvDnvBfA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
