grafana:
  client:
    secret: ENC[AES256_GCM,data:OC8jIpXbOtXNiEqEn9QWjHlvq7JgH5Dv+/OkJsqfia0=,iv:XzBg2X2eLmlJKACgxKZPu60Rr+sGEg39B2Vb0CRfMX8=,tag:mNehDdfnIJ1tb9bHUT02zQ==,type:str]
  security:
    secret_key: ENC[AES256_GCM,data:5oedHlrBJ9oa2tMSiZALHGk39yg=,iv:HhQYyYkFi+2WjFv/fpBmpRw8zhlZaEIZLITWrLa1KaY=,tag:3Zi7j+yMSfXY8HjQ6paEFg==,type:str]
sops:
  age:
    - recipient: age1h6la0udmehtp6h5z0ak0sz6a5phwtpyfk4uad2qztydy8mudrawslk5y3c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TVkzaXlpV0dyWGs1ZEh5
        anAyejNyRWtXdXJ1bG1PU1MzdHBPY1dNSFRBCnFyMTY0OXdEQ2ZsT2s1RzFDS2I2
        WTZrd1ZSNld4ajlvbm05MDdWa1paQTQKLS0tIDhBWEo1WlNRd0tFVzZIeFhWdnFQ
        YmFkOXFCZ0JWUXZaZGdrSDE1cTY5TzAKxBuWvDpxBtnx+/DrDVuSJfY2icBEC5Z7
        u4lTPVpe6k7W5ylEoR/umwoZkwTfBogH8vTfyomMkwASaBe258KK3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T13:22:59Z"
  mac: ENC[AES256_GCM,data:MU6FgFgZgdDEAZn0Mhbp2272zEYux/uE2QuV7AqCR6KYJs9yofOQs4Xx/hvSAi1NZqg2D62b1wfNSB5HC/Js3kPfAAaSo3JFiffD25Xi193QycWmFLTy+ockckX25gAa8i+gDyZDPqUWuBCHcZt21LMTrQGVw9bHMnrGHKuW8dk=,iv:h/IUHyItbeXGGnliQ9RptaQcrrJGYdGUN3/NmGIvymc=,tag:KwUKH3nr6QRqO0DxgQ01Qg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
