name: Run all update scripts

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 min
  workflow_dispatch: # Can be run manually

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Config Git
        run: |
          git config user.name "Culottes"
          git config user.email "culottes@sagbot.com"
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ {print $5; exit}')
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true

      - name: Make update scripts executable
        run: |
          chmod +x ci/update.sh
          chmod +x ci/script/*.sh || true

      - name: Run all update scripts
        run: ./ci/update.sh

      - name: Check for changes
        id: git_diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if needed
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "chore: auto-update scripts output"
          git push
